# Generated by Django 5.0.13 on 2025-04-03 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('title', models.CharField(max_length=50)),
                ('time_from', models.TimeField()),
                ('time_to', models.TimeField()),
            ],
        ),
    ]
