# Generated by Django 5.0.13 on 2025-04-03 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_event_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='title',
            new_name='name',
        ),
        migrations.AlterModelTable(
            name='event',
            table='Events',
        ),
    ]
