# Generated by Django 5.0.13 on 2025-04-03 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_event_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='event',
            table='app_event',
        ),
    ]
