# Generated by Django 5.0.13 on 2025-04-03 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_event_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='name',
            new_name='title',
        ),
    ]
