# Generated by Django 5.0.13 on 2025-04-03 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_name_event_title'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='event',
            table='app_event',
        ),
    ]
