# Generated by Django 5.0.13 on 2025-04-03 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_event_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='event',
            table='Events',
        ),
    ]
