# Generated by Django 5.0.13 on 2025-04-03 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_event_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Event',
            new_name='EventModel',
        ),
    ]
