# Generated by Django 5.0.13 on 2025-04-03 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_event_eventmodel'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='eventmodel',
            table='event_model',
        ),
    ]
