# Generated by Django 5.0.13 on 2025-04-03 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_eventmodel_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='eventmodel',
            table='Events',
        ),
    ]
