# Generated by Django 5.0.13 on 2025-04-03 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_eventmodel_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('time_from', models.TimeField()),
                ('time_to', models.TimeField()),
            ],
            options={
                'db_table': 'Events',
            },
        ),
        migrations.DeleteModel(
            name='EventModel',
        ),
    ]
