# Generated by Django 5.0.14 on 2025-08-15 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(db_column='EventCode', default=None, primary_key=True, serialize=False)),
                ('Day', models.IntegerField()),
                ('Month', models.IntegerField()),
                ('Year', models.IntegerField()),
                ('EventName', models.CharField(max_length=100)),
                ('TimeFrom', models.TimeField()),
                ('TimeTo', models.TimeField()),
                ('RoomID', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'events',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.AutoField(db_column='RoomCodeID', primary_key=True, serialize=False)),
                ('RoomCode', models.CharField(max_length=10)),
                ('RoomURL', models.URLField()),
            ],
            options={
                'db_table': 'room',
            },
        ),
    ]
